site_name: Portfolio
use_directory_urls: true

theme:
  name: material
  palette:
    primary: deep purple

markdown_extensions:
  - footnotes
  - attr_list
  - admonition

nav:
  - Leeswijzer: index.md
  - Analyseren: analyseren.md
  - Ontwerpen: ontwerpen.md
  - Realiseren: realiseren.md
  - Adviseren: adviseren.md
  - Beheer: beheer.md
  - Planning: planning.md
  - Blog: blog.md

