site_name: Portfolio
use_directory_urls: false

theme:
  name: material
  palette:
    primary: deep purple

markdown_extensions:
  - footnotes

nav:
  - Introductie: index.md
  - Analyseren: analyseren.md
  - Ontwerpen: ontwerpen.md
  - Realiseren: realiseren.md
  - Adviseren: adviseren.md
  - Onderhouden: onderhouden.md
  - Blog: blog.md

