site_name: Portfolio
use_directory_urls: true

theme:
  name: material
  palette:
    primary: deep purple

markdown_extensions:
  - footnotes
  - attr_list

nav:
  - Leeswijzer: leeswijzer.md
  - Introductie: introductie.md
  - Analyseren: analyseren.md
  - Ontwerpen: ontwerpen.md
  - Realiseren: realiseren.md
  - Adviseren: adviseren.md
  - Onderhouden: onderhouden.md
  - Blog: blog.md

